version: 2

on:
  workflow_dispatch:

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-breaking:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"